/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'

const IndexLazyRouteImport = createFileRoute('/')()
const CardIndexLazyRouteImport = createFileRoute('/card/')()
const InputIndexLazyRouteImport = createFileRoute('/input/')()
const TunaIndexLazyRouteImport = createFileRoute('/tuna/')()

const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const CardIndexLazyRoute = CardIndexLazyRouteImport.update({
  id: '/card/',
  path: '/card/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/card/index.lazy').then((d) => d.Route))
const InputIndexLazyRoute = InputIndexLazyRouteImport.update({
  id: '/input/',
  path: '/input/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/input/index.lazy').then((d) => d.Route))
const TunaIndexLazyRoute = TunaIndexLazyRouteImport.update({
  id: '/tuna/',
  path: '/tuna/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/tuna/index.lazy').then((d) => d.Route))

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/card/': typeof CardIndexLazyRoute
  '/input/': typeof InputIndexLazyRoute
  '/tuna/': typeof TunaIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/card': typeof CardIndexLazyRoute
  '/input': typeof InputIndexLazyRoute
  '/tuna': typeof TunaIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/card/': typeof CardIndexLazyRoute
  '/input/': typeof InputIndexLazyRoute
  '/tuna/': typeof TunaIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/card/' | '/input/' | '/tuna/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/card' | '/input' | '/tuna'
  id: '__root__' | '/' | '/card/' | '/input/' | '/tuna/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  CardIndexLazyRoute: typeof CardIndexLazyRoute
  InputIndexLazyRoute: typeof InputIndexLazyRoute
  TunaIndexLazyRoute: typeof TunaIndexLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/card/': {
      id: '/card/'
      path: '/card'
      fullPath: '/card/'
      preLoaderRoute: typeof CardIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/input/': {
      id: '/input/'
      path: '/input'
      fullPath: '/input/'
      preLoaderRoute: typeof InputIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tuna/': {
      id: '/tuna/'
      path: '/tuna'
      fullPath: '/tuna/'
      preLoaderRoute: typeof TunaIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  CardIndexLazyRoute: CardIndexLazyRoute,
  InputIndexLazyRoute: InputIndexLazyRoute,
  TunaIndexLazyRoute: TunaIndexLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
